import { classesTable, sectionsTable, studentsTable } from "@workspace/db";

export const studentListSelect = {
  id: studentsTable.id,
  admissionNumber: studentsTable.admissionNumber,
  rollNumber: studentsTable.rollNumber,
  firstName: studentsTable.firstName,
  middleName: studentsTable.middleName,
  lastName: studentsTable.lastName,
  gender: studentsTable.gender,
  dob: studentsTable.dob,
  bloodGroup: studentsTable.bloodGroup,
  photoUrl: studentsTable.photoUrl,
  classId: studentsTable.classId,
  className: classesTable.name,
  sectionId: studentsTable.sectionId,
  sectionName: sectionsTable.name,
  societyId: studentsTable.societyId,
  schoolId: studentsTable.schoolId,
  branchId: studentsTable.branchId,
  sessionId: studentsTable.sessionId,
  fatherName: studentsTable.fatherName,
  motherName: studentsTable.motherName,
  parentMobile: studentsTable.parentMobile,
  parentEmail: studentsTable.parentEmail,
  address: studentsTable.address,
  guardianName: studentsTable.guardianName,
  socialCategory: studentsTable.socialCategory,
  religion: studentsTable.religion,
  aadhaar: studentsTable.aadhaar,
  admissionDate: studentsTable.admissionDate,
  transportAssigned: studentsTable.transportAssigned,
  healthRecordId: studentsTable.healthRecordId,
  status: studentsTable.status,
  createdAt: studentsTable.createdAt,
};
