import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import organizationsRouter from "./organizations";
import sessionsRouter from "./sessions";
import schoolProfilesRouter from "./school-profiles";
import studentsRouter from "./students";
import studentRelationsRouter from "./student-relations";
import documentMasterRouter from "./document-master";
import entityDocumentsRouter from "./entity-documents";
import studentDocumentDashboardRouter from "./student-document-dashboard";
import usersRouter from "./users";
import classesRouter from "./classes";
import subjectsRouter from "./subjects";
import attendanceRouter from "./attendance";
import staffAttendanceRouter from "./staff-attendance";
import feesRouter from "./fees";
import feeStructuresRouter from "./fee-structures";
import examinationsRouter from "./examinations";
import udiseRouter from "./udise";
import announcementsRouter from "./announcements";
import admissionLeadsRouter from "./admission-leads";
import billingStubsRouter from "./billing-stubs";
import billingSettingsRouter from "./billing-settings";
import billingInvoicesRouter from "./billing-invoices";
import dashboardRouter from "./dashboard";
import analyticsRouter from "./analytics";
import rbacRouter from "./rbac";
import studentDocumentsRouter from "./student-documents";
import { requireAuthHandler } from "../lib/require-auth";
import { authorizeRequestHandler } from "../lib/authorize-request";

const router: IRouter = Router();

router.use(requireAuthHandler);
router.use(authorizeRequestHandler);

router.use(healthRouter);
router.use(authRouter);
router.use(organizationsRouter);
router.use(sessionsRouter);
router.use(schoolProfilesRouter);
router.use(studentDocumentDashboardRouter);
router.use(studentsRouter);
router.use(studentRelationsRouter);
router.use(documentMasterRouter);
router.use(entityDocumentsRouter);
router.use(studentDocumentsRouter);
router.use(usersRouter);
router.use(classesRouter);
router.use(subjectsRouter);
router.use(attendanceRouter);
router.use(staffAttendanceRouter);
router.use(feesRouter);
router.use(feeStructuresRouter);
router.use(billingSettingsRouter);
router.use(billingInvoicesRouter);
router.use(billingStubsRouter);
router.use(examinationsRouter);
router.use(udiseRouter);
router.use(announcementsRouter);
router.use(admissionLeadsRouter);
router.use(dashboardRouter);
router.use(analyticsRouter);
router.use(rbacRouter);

export default router;
